import { type ThemeBaseColor } from './theme-base-colors';
import { ThemeBorderRadius } from './theme-border-radiuses';
import { type ThemeBorderWidth } from './theme-border-widths';
import { type ThemeShadow } from './theme-shadows';
import { type ThemeFont } from './theme-fonts';
import { type ThemeMode } from './theme-modes';
import { type ThemeFontFamily } from './theme-font-families';
import { type ThemeHeadingFontFamily } from './theme-heading-font-families';
import { type ThemePrimaryColor } from './theme-primary-colors';
import { type ThemeSecondaryColor } from './theme-secondary-colors';
import { type ThemeStyle } from './theme-styles';
import { type ThemeTypeScale } from './theme-type-scales';
import { type ThemeTracking } from './theme-trackings';
import { type ThemeContainerWidth } from './theme-container-widths';
import { type ThemeMotion } from './theme-motions';

export type ThemeConfig = {
  font?: ThemeFont | string;
  mode?: ThemeMode | string;
  style?: ThemeStyle | string;
  borderRadius?: ThemeBorderRadius | string;
  borderWidth?: ThemeBorderWidth | string;
  shadow?: ThemeShadow | string;
  primaryColor?: ThemePrimaryColor | string;
  secondaryColor?: ThemeSecondaryColor | string;
  baseColor?: ThemeBaseColor | string;
  fontFamily?: ThemeFontFamily | string;
  headingFontFamily?: ThemeHeadingFontFamily | string;
  typeScale?: ThemeTypeScale | string;
  tracking?: ThemeTracking | string;
  containerWidth?: ThemeContainerWidth | string;
  motion?: ThemeMotion | string;
};
